lint:
  nextflow_config: false
  schema_params: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: The nf-core/eager community
  description: A fully reproducible and state-of-the-art ancient DNA analysis pipeline
  force: false
  is_nfcore: true
  name: eager
  org: nf-core
  outdir: .
  version: 3.0.0dev
