#!/bin/bash -l

#SBATCH --job-name "61genus"
#SBATCH --account p200123
#SBATCH --partition largemem
#SBATCH --qos default
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 128
#SBATCH --time 00-40:00:00
#SBATCH --output err/%x-%j.out
#SBATCH --error err/%x-%j.err
#SBATCH --mail-user amend.jin@gmail.com
#SBATCH --mail-type FAIL


source activate com_map

export PATH=/home/users/u100489/AMBER:$PATH


nextflow run com.nf \
	--fasta_info "/project/home/p200123/CHENYU/extract_authentication/61genus.info" \
	--reads "/project/home/p200123/CHENYU/DATA/EDNA/BISON/Steppe_bison.fastq.gz" \
	--fasta_index "/project/home/p200123/CHENYU/extract_authentication/index/61genus" \
	--threads 128 \
	--label "61genus" \
	-with-trace \
	-resume tiny_hypatia
